FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install -g npm
# Had to add this one by one as they were throwing not found errors on the npm run test step 
# RUN npm install react-scripts -g
# RUN npm install @testing-library/dom -g
# RUN npm install @testing-library/jest-dom -g

COPY . . 

CMD ["npm", "run", "start"]