FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install -g npm
RUN npm install react-scripts -g
RUN npm install @testing-library/dom -g
RUN npm install @testing-library/jest-dom -g

COPY . . 

CMD ["npm", "run", "start"]